### ISSUE TITLE
further needed requirements in INSTALLED_APPS setting

### ISSUE THREAD

**Issue by schoera** [bitmazk/django-multilingual-news#10]
Hi,
small enhancement of the **documentation** to make it easier for people unexperienced with your libs.

In your documentation (e.g. README.rst) there is a list of apps one needs to add to the INSTALLED_APPS setting. For me in a clean new (plain vanilla) django project it figured out that there are some apps missing (mainly because of further dependencies) to be abled to run the migrations.

(sorry for this "issue", because it's not a real code problem, but it took me some time to figure out the root cause and the list of apps ...)

with this app-list I was finally abled to run the migrations:
```
INSTALLED_APPS = (
    # requirements as shown in install instructions
    'django_libs',
    'multilingual_news',
    'people',
    'hvad',
    'multilingual_tags',
    'document_library',

    # further needed requirements 
    'menus',
    'easy_thumbnails',
    'cms',
    'treebeard',
    'filer',
)
```

**Comment by Tyrdall** [comment]
Sorry for the trouble.

README has been updated: https://github.com/bitmazk/django-multilingual-news/commit/793a7d27b94911892dcb8d33fbd4295f126b6b6e
