### ISSUE TITLE
How we add data into excert and content in new entry

### ISSUE THREAD

**Issue by kartikdanidhariya** [bitmazk/django-multilingual-news#11]
hi ,
i used django-multilingual-news==2.6.1
in admin when i add record in news entry so it not shows fields like "excert" and "content"
i want to know that how can i add data into "excert" and "content" field of news entry 
also i want to show those fields into news_entry_detail.html template
so how can i do that?

**Comment by Tyrdall** [comment]
Hi @kartikdanidhariya, I've just updated the README: https://github.com/bitmazk/django-multilingual-news#placeholders-excerpt-and-content

**Comment by kartikdanidhariya** [comment]
Thanks for you valuable reply...
